name: drupal-fe-assessment
recipe: drupal10
config:
  webroot: web
  php: '8.2'
  drush: ^10
  composer_version: '2.7.7'

tooling:
  drush:
    service: appserver
##  Enable line below for Windows, disable for MacOS.
#    cmd: php /app/vendor/drush/drush/drush
    env:
      DRUSH_OPTIONS_URI: drupal-fe-assessment.lndo.site
  phpcs-version:
    service: appserver
    description: "Check compliance for PHP 8.3"
    cmd:
      - /app/vendor/bin/phpcs -p --standard=PHPCompatibility --runtime-set testVersion 8.3- --extensions=php,module,inc,install,test,profile,theme,info
  phpcs-drupal:
    service: appserver
    description: "Check compliance for Drupal coding standards"
    cmd:
      - composer run code-sniff

proxy:
  phpmyadmin:
    - phpmyadmin.lndo.site

services:
  appserver:
    xdebug: true
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - localhost